import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, extname, basename, dirname } from 'node:path';

const ICONS_DIR = new URL('../icons/', import.meta.url).pathname;
const CORE_OUT = new URL('../src/core/icons.gen.ts', import.meta.url).pathname;
const SVG_OUT_DIR = new URL('../svg/', import.meta.url).pathname;

// Tabler-style canvas-bounds helper path — invisible, present in every source
// icon, and not part of the actual glyph.
const DEAD_PATH_D = 'M0 0h24v24H0z';

interface RawIcon {
  name: string;
  category: string;
  viewBox: string;
  paths: string[];
}

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(full)));
    } else if (extname(entry.name) === '.svg') {
      files.push(full);
    }
  }
  return files;
}

function parseSvg(source: string, name: string, category: string): RawIcon {
  const viewBoxMatch = source.match(/viewBox="([^"]+)"/);
  if (!viewBoxMatch) {
    throw new Error(`Icon "${name}" is missing a viewBox attribute`);
  }

  const paths = [...source.matchAll(/<path\b[^>]*\bd="([^"]+)"[^>]*\/?>/g)]
    .map((m) => m[1])
    .filter((d) => d.trim() !== DEAD_PATH_D);

  if (paths.length === 0) {
    throw new Error(`Icon "${name}" has no renderable path data`);
  }

  return { name, category, viewBox: viewBoxMatch[1], paths };
}

function cleanSvg(icon: RawIcon): string {
  const pathTags = icon.paths.map((d) => `  <path d="${d}" />`).join('\n');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${icon.viewBox}" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n${pathTags}\n</svg>\n`;
}

async function main() {
  const files = await walk(ICONS_DIR);
  if (files.length === 0) {
    throw new Error(`No .svg files found under ${ICONS_DIR}`);
  }

  const icons: RawIcon[] = [];
  const seen = new Set<string>();

  for (const file of files) {
    const name = basename(file, '.svg');
    const category = basename(dirname(file));

    if (seen.has(name)) {
      throw new Error(`Duplicate icon name "${name}" (icon names must be unique across categories)`);
    }
    seen.add(name);

    const source = await readFile(file, 'utf8');
    icons.push(parseSvg(source, name, category));
  }

  icons.sort((a, b) => a.name.localeCompare(b.name));

  const registryEntries = icons
    .map(
      (icon) =>
        `  '${icon.name}': { name: '${icon.name}', category: '${icon.category}', viewBox: '${icon.viewBox}', paths: [${icon.paths
          .map((d) => JSON.stringify(d))
          .join(', ')}] }`,
    )
    .join(',\n');

  const coreSource = `// Generated by scripts/build-icons.ts — do not edit by hand.
import type { IconData } from './types.js';

export const icons = {
${registryEntries}
} satisfies Record<string, IconData>;
`;

  await mkdir(dirname(CORE_OUT), { recursive: true });
  await writeFile(CORE_OUT, coreSource, 'utf8');

  await mkdir(SVG_OUT_DIR, { recursive: true });
  for (const icon of icons) {
    await writeFile(join(SVG_OUT_DIR, `${icon.name}.svg`), cleanSvg(icon), 'utf8');
  }

  console.log(`✅ generated ${icons.length} icon(s) → src/core/icons.gen.ts + svg/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
